version: 0.2
phases:
    build:
       commands:
         - pip install mkdocs
         - pip install mkdocs-material
         - mkdocs build --clean
    post_build:
      commands:
        ./deploy.sh
