version: 0.2
phases:
    install:
       commands:
         - pip install tox
    pre_build:
       commands:
         - chmod +x ./deploy.sh
    build:
       commands:
         - tox -e build
    post_build:
      commands:
        ./deploy.sh
